---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jack.
--- DateTime: 2018/10/31 15:46
---

local logger = luajava.bindClass("practice.feature.third.jar.lua.Logger")

function log()
    logger:log()
end

function log(inputParam)
    logger:log(inputParam)
end