/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class practice_feature_java_core_jni_HelloNative */

#ifndef _Included_practice_feature_java_core_jni_HelloNative
#define _Included_practice_feature_java_core_jni_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     practice_feature_java_core_jni_HelloNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_practice_feature_java_core_jni_HelloNative_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
