---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jack.
--- DateTime: 2018/10/30 21:07
---
require('init')

function main(inputParam)
    require("record")
    local record = CreateRecord(inputParam)
    log(record:getTest())
    record:setTest("hello world!")
    return record
end