---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jack.
--- DateTime: 2018/10/30 21:07
---
local logger = luajava.bindClass("practice.feature.third.jar.lua.Logger")

function main()
    logger:log()
    return "hello world!"
end